import type { Plan, PlanType, Ad, Category, User } from "./types";

// Payment Plans
export const plans: Plan[] = [
  {
    id: "plan-free",
    type: "free",
    name: "Grátis",
    nameEn: "Free",
    price: 0,
    currency: "BRL",
    duration: 30,
    maxAds: 3,
    displayPriority: 10,
    isActive: true,
    features: {
      maxActiveAds: 3,
      adDurationDays: 30,
      maxPhotosPerAd: 5,
      displayProbability: 0.4,
      positionBoost: 1,
      homepageSlots: 0,
      categoryHighlight: false,
      searchPriority: false,
      highlightedAds: false,
      featuredInCategory: false,
      priorityInSearch: false,
      maxImages: 5,
      videoAllowed: false,
      videoSupport: false,
      featuredBadge: false,
      urgentBadge: false,
      verifiedBadge: false,
      analytics: false,
      seoOptimization: false,
      socialMediaIntegration: false,
      boldTitle: false,
      coloredBackground: false,
      borderHighlight: false,
      largerThumbnail: false,
      socialSharing: false,
      statistics: false,
      autoRenew: false,
      prioritySupport: false,
      refreshesPerMonth: 0,
      bumpToTopPerMonth: 0,
    },
  },
  {
    id: "plan-basic",
    type: "basic",
    name: "Básico",
    nameEn: "Basic",
    price: 29.90,
    currency: "BRL",
    duration: 30,
    maxAds: 10,
    displayPriority: 30,
    isActive: true,
    features: {
      maxActiveAds: 10,
      adDurationDays: 45,
      maxPhotosPerAd: 10,
      displayProbability: 0.65,
      positionBoost: 1.2,
      homepageSlots: 0,
      categoryHighlight: false,
      searchPriority: false,
      highlightedAds: false,
      featuredInCategory: false,
      priorityInSearch: false,
      maxImages: 10,
      videoAllowed: false,
      videoSupport: false,
      featuredBadge: false,
      urgentBadge: false,
      verifiedBadge: false,
      analytics: false,
      seoOptimization: false,
      socialMediaIntegration: false,
      boldTitle: false,
      coloredBackground: false,
      borderHighlight: false,
      largerThumbnail: false,
      socialSharing: true,
      statistics: true,
      autoRenew: true,
      prioritySupport: false,
      refreshesPerMonth: 2,
      bumpToTopPerMonth: 0,
    },
  },
  {
    id: "plan-premium",
    type: "premium",
    name: "Premium",
    nameEn: "Premium",
    price: 79.90,
    currency: "BRL",
    duration: 30,
    maxAds: 25,
    displayPriority: 60,
    isActive: true,
    features: {
      maxActiveAds: 25,
      adDurationDays: 60,
      maxPhotosPerAd: 20,
      displayProbability: 0.85,
      positionBoost: 1.5,
      homepageSlots: 2,
      categoryHighlight: true,
      searchPriority: true,
      highlightedAds: true,
      featuredInCategory: true,
      priorityInSearch: true,
      maxImages: 20,
      videoAllowed: true,
      videoSupport: true,
      featuredBadge: false,
      urgentBadge: true,
      verifiedBadge: true,
      analytics: true,
      seoOptimization: true,
      socialMediaIntegration: true,
      boldTitle: true,
      coloredBackground: false,
      borderHighlight: true,
      largerThumbnail: true,
      socialSharing: true,
      statistics: true,
      autoRenew: true,
      prioritySupport: false,
      refreshesPerMonth: 5,
      bumpToTopPerMonth: 2,
    },
  },
  {
    id: "plan-featured",
    type: "featured",
    name: "Destaque",
    nameEn: "Featured",
    price: 149.90,
    currency: "BRL",
    duration: 30,
    maxAds: 50,
    displayPriority: 85,
    isActive: true,
    features: {
      maxActiveAds: 50,
      adDurationDays: 90,
      maxPhotosPerAd: 30,
      displayProbability: 0.95,
      positionBoost: 2.0,
      homepageSlots: 4,
      categoryHighlight: true,
      searchPriority: true,
      highlightedAds: true,
      featuredInCategory: true,
      priorityInSearch: true,
      maxImages: 30,
      videoAllowed: true,
      videoSupport: true,
      featuredBadge: true,
      urgentBadge: true,
      verifiedBadge: true,
      analytics: true,
      seoOptimization: true,
      socialMediaIntegration: true,
      boldTitle: true,
      coloredBackground: true,
      borderHighlight: true,
      largerThumbnail: true,
      socialSharing: true,
      statistics: true,
      autoRenew: true,
      prioritySupport: true,
      refreshesPerMonth: 10,
      bumpToTopPerMonth: 5,
    },
  },
  {
    id: "plan-enterprise",
    type: "enterprise",
    name: "Empresarial",
    nameEn: "Enterprise",
    price: 299.90,
    currency: "BRL",
    duration: 30,
    maxAds: -1, // unlimited
    displayPriority: 100,
    isActive: true,
    features: {
      maxActiveAds: -1,
      adDurationDays: 120,
      maxPhotosPerAd: 50,
      displayProbability: 1.0,
      positionBoost: 3.0,
      homepageSlots: 8,
      categoryHighlight: true,
      searchPriority: true,
      highlightedAds: true,
      featuredInCategory: true,
      priorityInSearch: true,
      maxImages: 50,
      videoAllowed: true,
      videoSupport: true,
      featuredBadge: true,
      urgentBadge: true,
      verifiedBadge: true,
      analytics: true,
      seoOptimization: true,
      socialMediaIntegration: true,
      boldTitle: true,
      coloredBackground: true,
      borderHighlight: true,
      largerThumbnail: true,
      socialSharing: true,
      statistics: true,
      autoRenew: true,
      prioritySupport: true,
      refreshesPerMonth: -1, // unlimited
      bumpToTopPerMonth: -1, // unlimited
    },
  },
];

// Categories
export const categories: Category[] = [
  {
    id: "cat-vehicles",
    name: "Veículos",
    slug: "veiculos",
    icon: "🚗",
    adCount: 1250,
    isActive: true,
    subcategories: [
      { id: "sub-cars", name: "Carros", slug: "carros", icon: "🚗", adCount: 850, isActive: true },
      { id: "sub-motos", name: "Motos", slug: "motos", icon: "🏍️", adCount: 280, isActive: true },
      { id: "sub-trucks", name: "Caminhões", slug: "caminhoes", icon: "🚛", adCount: 120, isActive: true },
    ],
  },
  {
    id: "cat-realestate",
    name: "Imóveis",
    slug: "imoveis",
    icon: "🏠",
    adCount: 980,
    isActive: true,
    subcategories: [
      { id: "sub-apartments", name: "Apartamentos", slug: "apartamentos", icon: "🏢", adCount: 450, isActive: true },
      { id: "sub-houses", name: "Casas", slug: "casas", icon: "🏡", adCount: 380, isActive: true },
      { id: "sub-land", name: "Terrenos", slug: "terrenos", icon: "🌳", adCount: 150, isActive: true },
    ],
  },
  {
    id: "cat-electronics",
    name: "Eletrônicos",
    slug: "eletronicos",
    icon: "📱",
    adCount: 2100,
    isActive: true,
    subcategories: [
      { id: "sub-phones", name: "Celulares", slug: "celulares", icon: "📱", adCount: 890, isActive: true },
      { id: "sub-computers", name: "Computadores", slug: "computadores", icon: "💻", adCount: 650, isActive: true },
      { id: "sub-games", name: "Games", slug: "games", icon: "🎮", adCount: 560, isActive: true },
    ],
  },
  {
    id: "cat-fashion",
    name: "Moda",
    slug: "moda",
    icon: "👕",
    adCount: 1560,
    isActive: true,
    subcategories: [
      { id: "sub-clothes", name: "Roupas", slug: "roupas", icon: "👔", adCount: 980, isActive: true },
      { id: "sub-shoes", name: "Calçados", slug: "calcados", icon: "👟", adCount: 380, isActive: true },
      { id: "sub-accessories", name: "Acessórios", slug: "acessorios", icon: "👜", adCount: 200, isActive: true },
    ],
  },
  {
    id: "cat-services",
    name: "Serviços",
    slug: "servicos",
    icon: "🔧",
    adCount: 780,
    isActive: true,
    subcategories: [
      { id: "sub-construction", name: "Construção", slug: "construcao", icon: "🏗️", adCount: 320, isActive: true },
      { id: "sub-domestic", name: "Domésticos", slug: "domesticos", icon: "🏠", adCount: 280, isActive: true },
      { id: "sub-tech", name: "Tecnologia", slug: "tecnologia", icon: "💻", adCount: 180, isActive: true },
    ],
  },
  {
    id: "cat-jobs",
    name: "Empregos",
    slug: "empregos",
    icon: "💼",
    adCount: 1890,
    isActive: true,
    subcategories: [
      { id: "sub-fulltime", name: "Tempo Integral", slug: "tempo-integral", icon: "⏰", adCount: 890, isActive: true },
      { id: "sub-parttime", name: "Meio Período", slug: "meio-periodo", icon: "⏱️", adCount: 560, isActive: true },
      { id: "sub-freelance", name: "Freelance", slug: "freelance", icon: "🏠", adCount: 440, isActive: true },
    ],
  },
];

// Sample Users
export const sampleUsers: User[] = [
  {
    id: "user-1",
    email: "joao.silva@email.com",
    name: "João Silva",
    phone: "11999887766",
    type: "individual",
    currentPlanId: "plan-premium",
    rating: 4.8,
    totalAds: 15,
    activeAds: 8,
    memberSince: "2023-06-15",
    isVerified: true,
    isActive: true,
  },
  {
    id: "user-2",
    email: "automoveis.sp@email.com",
    name: "Automóveis SP",
    phone: "11988776655",
    type: "business",
    businessInfo: {
      companyName: "Automóveis SP Ltda",
      cnpj: "12.345.678/0001-90",
      address: "Av. Paulista, 1000 - São Paulo, SP",
      website: "https://automoveissp.com.br",
    },
    currentPlanId: "plan-enterprise",
    rating: 4.9,
    totalAds: 120,
    activeAds: 85,
    memberSince: "2022-01-10",
    isVerified: true,
    isActive: true,
  },
  {
    id: "user-3",
    email: "maria.santos@email.com",
    name: "Maria Santos",
    phone: "21977665544",
    type: "individual",
    currentPlanId: "plan-basic",
    rating: 4.5,
    totalAds: 8,
    activeAds: 3,
    memberSince: "2024-03-20",
    isVerified: true,
    isActive: true,
  },
];

// Helper to generate display settings based on plan
function getDisplaySettings(planType: PlanType) {
  const plan = plans.find((p) => p.type === planType);
  if (!plan) return defaultDisplaySettings;

  const badges = [];
  if (plan.features.featuredBadge) badges.push({ type: "featured" as const, label: "Destaque", color: "amber" });
  if (plan.features.verifiedBadge) badges.push({ type: "verified" as const, label: "Verificado", color: "blue" });

  return {
    priority: plan.displayPriority,
    displayProbability: plan.features.displayProbability,
    badges,
    style: {
      boldTitle: plan.features.boldTitle,
      backgroundColor: plan.features.coloredBackground ? "#fffbeb" : undefined,
      borderColor: plan.features.borderHighlight ? "#f59e0b" : undefined,
      thumbnailSize: plan.features.largerThumbnail ? "large" as const : "normal" as const,
    },
  };
}

const defaultDisplaySettings = {
  priority: 10,
  displayProbability: 0.4,
  badges: [],
  style: {
    boldTitle: false,
    thumbnailSize: "normal" as const,
  },
};

// Sample Ads
export const sampleAds: Ad[] = [
  // Enterprise/Featured Ads
  {
    id: "ad-1",
    userId: "user-2",
    planId: "plan-enterprise",
    planType: "enterprise",
    title: "Honda Civic EXL 2023 - Único Dono - Garantia de Fábrica",
    slug: "honda-civic-exl-2023-unico-dono",
    description: "Honda Civic EXL 2023 com apenas 15.000km rodados. Carro em perfeito estado, único dono, todas as revisões feitas na concessionária. Aceito troca por veículo de menor valor.",
    price: 145000,
    currency: "BRL",
    negotiable: true,
    categoryId: "cat-vehicles",
    subcategoryId: "sub-cars",
    condition: "like_new",
    location: {
      country: "Brasil",
      state: "SP",
      city: "São Paulo",
      neighborhood: "Moema",
    },
    images: [
      { id: "img-1", url: "/ads/civic-1.jpg", thumbnailUrl: "/ads/civic-1-thumb.jpg", alt: "Honda Civic frente", order: 1, isPrimary: true },
      { id: "img-2", url: "/ads/civic-2.jpg", thumbnailUrl: "/ads/civic-2-thumb.jpg", alt: "Honda Civic lateral", order: 2, isPrimary: false },
    ],
    contact: {
      name: "Automóveis SP",
      phone: "11988776655",
      whatsapp: "11988776655",
      email: "contato@automoveissp.com.br",
      showPhone: true,
      showWhatsapp: true,
      showEmail: true,
    },
    status: "active",
    createdAt: "2025-01-15T10:00:00Z",
    updatedAt: "2025-01-20T08:00:00Z",
    publishedAt: "2025-01-15T12:00:00Z",
    expiresAt: "2025-02-15T12:00:00Z",
    views: 2450,
    favorites: 89,
    contacts: 34,
    displaySettings: getDisplaySettings("enterprise"),
    tags: ["honda", "civic", "sedan", "2023", "automatico"],
  },
  {
    id: "ad-2",
    userId: "user-2",
    planId: "plan-enterprise",
    planType: "enterprise",
    title: "Toyota Corolla Cross XRE 2024 - 0KM - Pronta Entrega",
    slug: "toyota-corolla-cross-xre-2024-0km",
    description: "Corolla Cross XRE 2024 zero quilômetro, pronta entrega! Todas as cores disponíveis. Financiamento em até 60x. Aceitamos seu usado na troca.",
    price: 189900,
    currency: "BRL",
    negotiable: false,
    categoryId: "cat-vehicles",
    subcategoryId: "sub-cars",
    condition: "new",
    location: {
      country: "Brasil",
      state: "SP",
      city: "São Paulo",
      neighborhood: "Itaim Bibi",
    },
    images: [
      { id: "img-3", url: "/ads/corolla-1.jpg", thumbnailUrl: "/ads/corolla-1-thumb.jpg", alt: "Toyota Corolla Cross", order: 1, isPrimary: true },
    ],
    contact: {
      name: "Automóveis SP",
      phone: "11988776655",
      whatsapp: "11988776655",
      showPhone: true,
      showWhatsapp: true,
      showEmail: false,
    },
    status: "active",
    createdAt: "2025-01-18T14:00:00Z",
    updatedAt: "2025-01-20T09:00:00Z",
    publishedAt: "2025-01-18T15:00:00Z",
    expiresAt: "2025-02-18T15:00:00Z",
    views: 1890,
    favorites: 67,
    contacts: 28,
    displaySettings: getDisplaySettings("enterprise"),
    tags: ["toyota", "corolla", "suv", "2024", "0km", "novo"],
  },

  // Featured Ads
  {
    id: "ad-3",
    userId: "user-1",
    planId: "plan-featured",
    planType: "featured",
    title: "iPhone 15 Pro Max 256GB - Na Caixa - Nota Fiscal",
    slug: "iphone-15-pro-max-256gb-na-caixa",
    description: "iPhone 15 Pro Max 256GB Titanium Natural. Comprado em dezembro/2024, ainda na garantia Apple. Acompanha caixa, carregador e nota fiscal. Motivo da venda: ganhei outro.",
    price: 7500,
    currency: "BRL",
    negotiable: true,
    categoryId: "cat-electronics",
    subcategoryId: "sub-phones",
    condition: "like_new",
    location: {
      country: "Brasil",
      state: "SP",
      city: "São Paulo",
      neighborhood: "Pinheiros",
    },
    images: [
      { id: "img-4", url: "/ads/iphone-1.jpg", thumbnailUrl: "/ads/iphone-1-thumb.jpg", alt: "iPhone 15 Pro Max", order: 1, isPrimary: true },
    ],
    contact: {
      name: "João Silva",
      phone: "11999887766",
      whatsapp: "11999887766",
      showPhone: false,
      showWhatsapp: true,
      showEmail: false,
    },
    status: "active",
    createdAt: "2025-01-17T09:00:00Z",
    updatedAt: "2025-01-19T14:00:00Z",
    publishedAt: "2025-01-17T10:00:00Z",
    expiresAt: "2025-02-17T10:00:00Z",
    views: 3200,
    favorites: 145,
    contacts: 52,
    displaySettings: getDisplaySettings("featured"),
    tags: ["iphone", "apple", "celular", "smartphone", "15 pro max"],
  },

  // Premium Ads
  {
    id: "ad-4",
    userId: "user-1",
    planId: "plan-premium",
    planType: "premium",
    title: "Apartamento 3 Quartos - Jardins - 120m²",
    slug: "apartamento-3-quartos-jardins-120m2",
    description: "Lindo apartamento nos Jardins com 3 quartos (1 suíte), 2 vagas, varanda gourmet. Prédio com piscina, academia e salão de festas. Aceita financiamento.",
    price: 950000,
    currency: "BRL",
    negotiable: true,
    categoryId: "cat-realestate",
    subcategoryId: "sub-apartments",
    condition: "good",
    location: {
      country: "Brasil",
      state: "SP",
      city: "São Paulo",
      neighborhood: "Jardins",
    },
    images: [
      { id: "img-5", url: "/ads/apt-1.jpg", thumbnailUrl: "/ads/apt-1-thumb.jpg", alt: "Sala do apartamento", order: 1, isPrimary: true },
    ],
    contact: {
      name: "João Silva",
      phone: "11999887766",
      whatsapp: "11999887766",
      email: "joao.silva@email.com",
      showPhone: true,
      showWhatsapp: true,
      showEmail: true,
    },
    status: "active",
    createdAt: "2025-01-10T11:00:00Z",
    updatedAt: "2025-01-18T16:00:00Z",
    publishedAt: "2025-01-10T12:00:00Z",
    expiresAt: "2025-02-10T12:00:00Z",
    views: 1560,
    favorites: 78,
    contacts: 23,
    displaySettings: getDisplaySettings("premium"),
    tags: ["apartamento", "3 quartos", "jardins", "são paulo", "venda"],
  },

  // Basic Ads
  {
    id: "ad-5",
    userId: "user-3",
    planId: "plan-basic",
    planType: "basic",
    title: "PlayStation 5 + 2 Controles + 5 Jogos",
    slug: "playstation-5-2-controles-5-jogos",
    description: "PS5 em ótimo estado, pouco uso. Acompanha 2 controles originais e 5 jogos: FIFA 24, Spider-Man 2, God of War, Horizon e Gran Turismo 7.",
    price: 3200,
    currency: "BRL",
    negotiable: true,
    categoryId: "cat-electronics",
    subcategoryId: "sub-games",
    condition: "good",
    location: {
      country: "Brasil",
      state: "RJ",
      city: "Rio de Janeiro",
      neighborhood: "Copacabana",
    },
    images: [
      { id: "img-6", url: "/ads/ps5-1.jpg", thumbnailUrl: "/ads/ps5-1-thumb.jpg", alt: "PlayStation 5", order: 1, isPrimary: true },
    ],
    contact: {
      name: "Maria Santos",
      whatsapp: "21977665544",
      showPhone: false,
      showWhatsapp: true,
      showEmail: false,
    },
    status: "active",
    createdAt: "2025-01-12T15:00:00Z",
    updatedAt: "2025-01-16T10:00:00Z",
    publishedAt: "2025-01-12T16:00:00Z",
    expiresAt: "2025-02-12T16:00:00Z",
    views: 890,
    favorites: 45,
    contacts: 12,
    displaySettings: getDisplaySettings("basic"),
    tags: ["ps5", "playstation", "games", "sony", "console"],
  },

  // Free Ads
  {
    id: "ad-6",
    userId: "user-3",
    planId: "plan-free",
    planType: "free",
    title: "Bicicleta Caloi Aro 29 - Usada",
    slug: "bicicleta-caloi-aro-29-usada",
    description: "Bicicleta Caloi aro 29, 21 marchas. Usada mas em bom estado. Ideal para trilhas e uso urbano. Pequenos arranhões na pintura.",
    price: 800,
    currency: "BRL",
    negotiable: true,
    categoryId: "cat-vehicles",
    subcategoryId: "sub-motos",
    condition: "fair",
    location: {
      country: "Brasil",
      state: "RJ",
      city: "Rio de Janeiro",
      neighborhood: "Tijuca",
    },
    images: [
      { id: "img-7", url: "/ads/bike-1.jpg", thumbnailUrl: "/ads/bike-1-thumb.jpg", alt: "Bicicleta Caloi", order: 1, isPrimary: true },
    ],
    contact: {
      name: "Maria",
      whatsapp: "21977665544",
      showPhone: false,
      showWhatsapp: true,
      showEmail: false,
    },
    status: "active",
    createdAt: "2025-01-08T09:00:00Z",
    updatedAt: "2025-01-08T09:00:00Z",
    publishedAt: "2025-01-08T10:00:00Z",
    expiresAt: "2025-02-08T10:00:00Z",
    views: 234,
    favorites: 8,
    contacts: 3,
    displaySettings: getDisplaySettings("free"),
    tags: ["bicicleta", "caloi", "bike", "aro 29"],
  },

  // More sample ads for variety
  {
    id: "ad-7",
    userId: "user-2",
    planId: "plan-featured",
    planType: "featured",
    title: "Jeep Compass Limited 2024 - Diesel - 4x4",
    slug: "jeep-compass-limited-2024-diesel-4x4",
    description: "Jeep Compass Limited 2024, diesel, tração 4x4. Carro top de linha com todos os opcionais. Teto solar panorâmico, bancos em couro, multimídia de 10 polegadas.",
    price: 235000,
    currency: "BRL",
    negotiable: true,
    categoryId: "cat-vehicles",
    subcategoryId: "sub-cars",
    condition: "new",
    location: {
      country: "Brasil",
      state: "SP",
      city: "São Paulo",
      neighborhood: "Vila Olímpia",
    },
    images: [
      { id: "img-8", url: "/ads/jeep-1.jpg", thumbnailUrl: "/ads/jeep-1-thumb.jpg", alt: "Jeep Compass", order: 1, isPrimary: true },
    ],
    contact: {
      name: "Automóveis SP",
      phone: "11988776655",
      whatsapp: "11988776655",
      showPhone: true,
      showWhatsapp: true,
      showEmail: false,
    },
    status: "active",
    createdAt: "2025-01-19T08:00:00Z",
    updatedAt: "2025-01-20T07:00:00Z",
    publishedAt: "2025-01-19T09:00:00Z",
    expiresAt: "2025-02-19T09:00:00Z",
    views: 1120,
    favorites: 56,
    contacts: 18,
    displaySettings: getDisplaySettings("featured"),
    tags: ["jeep", "compass", "suv", "diesel", "4x4", "2024"],
  },
  {
    id: "ad-8",
    userId: "user-1",
    planId: "plan-premium",
    planType: "premium",
    title: "MacBook Pro M3 14\" - 18GB RAM - 512GB SSD",
    slug: "macbook-pro-m3-14-18gb-512gb",
    description: "MacBook Pro com chip M3, tela de 14 polegadas, 18GB de memória unificada e 512GB de armazenamento SSD. Na caixa, com nota fiscal e garantia Apple até 2026.",
    price: 14500,
    currency: "BRL",
    negotiable: true,
    categoryId: "cat-electronics",
    subcategoryId: "sub-computers",
    condition: "like_new",
    location: {
      country: "Brasil",
      state: "SP",
      city: "São Paulo",
      neighborhood: "Moema",
    },
    images: [
      { id: "img-9", url: "/ads/macbook-1.jpg", thumbnailUrl: "/ads/macbook-1-thumb.jpg", alt: "MacBook Pro M3", order: 1, isPrimary: true },
    ],
    contact: {
      name: "João Silva",
      whatsapp: "11999887766",
      showPhone: false,
      showWhatsapp: true,
      showEmail: false,
    },
    status: "active",
    createdAt: "2025-01-16T13:00:00Z",
    updatedAt: "2025-01-18T11:00:00Z",
    publishedAt: "2025-01-16T14:00:00Z",
    expiresAt: "2025-02-16T14:00:00Z",
    views: 2100,
    favorites: 98,
    contacts: 31,
    displaySettings: getDisplaySettings("premium"),
    tags: ["macbook", "apple", "notebook", "m3", "laptop"],
  },
];

// Helper functions
export function getPlanById(id: string): Plan | undefined {
  return plans.find((p) => p.id === id);
}

export function getPlanByType(type: PlanType): Plan | undefined {
  return plans.find((p) => p.type === type);
}

export function getCategoryById(id: string): Category | undefined {
  return categories.find((c) => c.id === id);
}

export function getCategoryBySlug(slug: string): Category | undefined {
  return categories.find((c) => c.slug === slug);
}

export function getAdById(id: string): Ad | undefined {
  return sampleAds.find((a) => a.id === id);
}

export function getUserById(id: string): User | undefined {
  return sampleUsers.find((u) => u.id === id);
}

// Aliases for convenience
export const samplePlans = plans;
export const sampleCategories = categories;
